sudo: required

language: php
php:
  - 7.0

env:
  - NODE_RELEASE=6.x

before_install:
  - sudo rm -rf ~/.nvm
  - curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}" | sudo -E bash -
  - sudo apt-get install -y nodejs
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@4; fi

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - npm install
  - npm install gulp
  - gulp materialize-build
  - gulp

script:
  - vendor/bin/phpunit