language: php
php:
  - '7.0'
env:
  - DB=mysql
  APP_ENV: testing
  APP_KEY: b29c11b3ebbf41ec92e4fdafe00a479b

install:
  - npm install
  - composer install --no-interaction --prefer-dist --no-suggest

cache:
directories:
  - $HOME/.composer/cache

before_install:
  - if [[ $TRAVIS_PHP_VERSION != 7.1 ]] ; then phpenv config-rm xdebug.ini; fi

script: vendor/bin/phpunit

notifications:
  email: "vinayak@shoptreeapp.com" 
