language: php
php:
  - '7.0'
env:
  - DB=mysql

install:
  - npm install
  - composer install
  - php artisan key:generate

before_install:
  - if [[ $TRAVIS_PHP_VERSION != 7.1 ]] ; then phpenv config-rm xdebug.ini; fi
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

script: vendor/bin/phpunit

notifications:
  email: "vinayak@shoptreeapp.com" 
